version: "3"
services:
  dns:
    image: rohscx/bind-alpine
    ports:
        - "53:53/udp"
    env_file:
      - bind.env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - DNS
networks:
  DNS:
